version: '3'
services:
  apache:
    build: .docker/apache
    container_name: sf4_apache
    ports:
      - "80:80"
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/sf4
    depends_on:
      - php

  mysql:
    image: mysql:8
    container_name: sf4_mysql
    ports:
      - "3306:3306"
    volumes:
      - .docker/data/db:/var/lib/mysql
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf4
      MYSQL_USER: sf4
      MYSQL_PASSWORD: sf4

  php:
    build: .docker/php
    container_name: sf4_php
    volumes:
      - .:/home/wwwroot/sf4
    environment:
      - maildev_host=sf4_maildev
    depends_on:
      - maildev
      - mysql
      - mongodb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf4_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80"
    links:
      - mysql

  maildev:
    image: djfarrelly/maildev
    container_name: sf4_maildev
    ports:
      - "25"
      - "8001:80"

  mongodb:
    build:
      context: .docker/mongodb
      dockerfile: Dockerfile.mongodb
      args:
        mongodb_initdb_database: symfony
        mongodb_password: symfony
        mongodb_username: symfony
    environment:
      MONGO_INITDB_DATABASE: symfony
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGODB_PASSWORD: symfony
      MONGODB_SERVER: mongodb://mongodb:27017
      MONGODB_USERNAME: symfony
      TZ: Europe/Paris
    env_file:
      - .env
    networks:
      default: null
    ports:
    - mode: ingress
      target: 27017
      published: 27017
      protocol: tcp
    volumes:
    - type: bind
      source: .docker/mongodb/data/db
      target: /data/db